version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - kotlin

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: Europe/London
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Europe/London
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions