CREATE TABLE destinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    average_cost NUMERIC(10, 2) NOT NULL,
    climate VARCHAR(20) NOT NULL,
    flight_time_hours NUMERIC(4, 1) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT destinations_average_cost_non_negative
        CHECK (average_cost >= 0),

    CONSTRAINT destinations_flight_time_positive
        CHECK (flight_time_hours > 0),

    CONSTRAINT destinations_climate_valid
        CHECK (climate IN ('WARM', 'MILD', 'COLD')),

    CONSTRAINT destinations_city_country_unique
        UNIQUE (city, country)
);


CREATE TABLE destination_interests (
    destination_id BIGINT NOT NULL,
    interest VARCHAR(50) NOT NULL,

    CONSTRAINT destination_interests_primary_key
        PRIMARY KEY (destination_id, interest),

    CONSTRAINT destination_interests_destination_fk
        FOREIGN KEY (destination_id)
        REFERENCES destinations (id)
        ON DELETE CASCADE
);

CREATE INDEX destinations_average_cost_idx
    ON destinations (average_cost);

CREATE INDEX destinations_climate_idx
    ON destinations (climate);

CREATE INDEX destination_interests_interest_idx
    ON destination_interests (interest);